# Get editor completions based on the config schema
"$schema" = 'https://starship.rs/config-schema.json'

# Inserts a blank line between shell prompts
add_newline = true

right_format = """$kubernetes $time"""

# Replace the 'â¯' symbol in the prompt with 'âœ'
[character] # The name of the module we are configuring is 'character'
success_symbol = '[âœ](bold green)' # The 'success_symbol' segment is being set to 'âœ' with the color 'bold green'
error_symbol = "[âœ—](bold red)"

# Disable the package module, hiding it from the prompt completely
[package]
disabled = true

[azure]
disabled = true
format = 'on [$symbol($subscription)]($style) '
symbol = 'ï´ƒ '
style = 'blue bold'

[kubernetes]
format = 'on [ïŠ›  $context|$namespace](bright-purple) '
disabled = false

[git_branch]
symbol = "ğŸŒ± "

[git_commit]
tag_symbol = "ğŸ”– "

[git_status]
conflicted = "="
ahead = "â‡¡${count}"
behind = "â‡£${count}"
diverged = "â‡•â‡¡${ahead_count}â‡£${behind_count}"
up_to_date = "âœ“"
untracked = "?"
stashed = "$"
modified = "ğŸ› ï¸ x${count} "
staged = '[++\($count\)](green)'
renamed = "Â»"
deleted = 'ğŸ—‘ï¸ Ã—${count}'

[nodejs]
format = ''
detect_folders = ['!/Users/Jan.Wacker']

[terraform]
format = '[ğŸ ğŸ’¨ $workspace]($style) '
style = 'bold 105'

[time]
disabled = false
format = '$time'
time_format = '%T'
utc_time_offset = '+2'


